apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openedx
resources:
  - migrate.yaml
images:
  - name: registry.example.com/ai-server-backend
    newName: registry.example.com/ai-server-backend
    newTag: 25.9.16.7.2.64.16.5.7.2.18
