'use client'
import { useEffect, useState } from 'react'
import { getCoursePolicy, updateCoursePolicy } from '../../lib/api'
import { CoursePolicy, CoursePolicyUpdate } from '../../types'
import { ActionMessage, ActionMessageData, toUserError } from '../ui/ActionMessage'
import { LoadingButton } from '../ui/LoadingButton'
export function CoursePolicyPanel({ courseId, headers, writeHeaders, canEdit }: { courseId: string; headers: HeadersInit; writeHeaders: HeadersInit; canEdit: boolean }) {
  const [policy, setPolicy] = useState<CoursePolicy | null>(null); const [form, setForm] = useState<CoursePolicyUpdate | null>(null); const [message, setMessage] = useState<ActionMessageData | null>(null); const [loading, setLoading] = useState(false)
  async function load(){ setLoading(true); try{ const d=await getCoursePolicy(courseId,headers); setPolicy(d); setForm({course_id:d.course_id,monthly_budget_usd:d.monthly_budget_usd,max_questions_per_course:d.max_questions_per_course,max_questions_per_job:d.max_questions_per_job,max_retry:d.max_retry}) }catch(e){ setMessage(toUserError(e)) }finally{ setLoading(false) } }
  useEffect(()=>{load()},[courseId])
  async function save(){ if(!form)return; setLoading(true); try{ const d=await updateCoursePolicy(form,writeHeaders); setPolicy(d); setForm({course_id:d.course_id,monthly_budget_usd:d.monthly_budget_usd,max_questions_per_course:d.max_questions_per_course,max_questions_per_job:d.max_questions_per_job,max_retry:d.max_retry}); setMessage({type:'success',title:'Đã lưu giới hạn khóa học',body:'Các lượt tạo câu hỏi tiếp theo sẽ dùng giới hạn mới.'}) }catch(e){ setMessage(toUserError(e)) }finally{ setLoading(false) } }
  function setNumber(name:keyof CoursePolicyUpdate,value:number){ if(form)setForm({...form,[name]:value}) }
  return <section className="card"><div className="section-head"><div><h2>Giới hạn tạo câu hỏi theo khóa học</h2><p className="helper">Cấu hình tổng số câu có thể tạo trong khóa học và số câu tối đa mỗi lượt. Backend vẫn kiểm tra hard stop.</p></div><LoadingButton className="btn secondary" loading={loading} onClick={load}>Tải lại</LoadingButton></div><ActionMessage message={message} onClose={()=>setMessage(null)}/>{policy&&<div className="summary-grid"><div><span>Đã tạo</span><b>{policy.generated_questions}</b></div><div><span>Còn lại</span><b>{policy.remaining_questions}</b></div><div><span>Tối đa/khóa</span><b>{policy.max_questions_per_course}</b></div><div><span>Tối đa/lượt</span><b>{policy.max_questions_per_job}</b></div></div>}{form&&<div className="grid grid-4"><div><label>Ngân sách tháng USD</label><input className="input" type="number" disabled={!canEdit} value={form.monthly_budget_usd} onChange={e=>setNumber('monthly_budget_usd',Number(e.target.value))}/></div><div><label>Số câu tối đa trong khóa</label><input className="input" type="number" disabled={!canEdit} value={form.max_questions_per_course} onChange={e=>setNumber('max_questions_per_course',Number(e.target.value))}/></div><div><label>Số câu tối đa mỗi lượt</label><input className="input" type="number" disabled={!canEdit} value={form.max_questions_per_job} onChange={e=>setNumber('max_questions_per_job',Number(e.target.value))}/></div><div><label>Retry tối đa</label><input className="input" type="number" disabled={!canEdit} value={form.max_retry} onChange={e=>setNumber('max_retry',Number(e.target.value))}/></div></div>}{canEdit&&<div className="button-row"><LoadingButton className="btn" loading={loading} onClick={save}>Lưu giới hạn</LoadingButton></div>}</section>
}
