"""Tutor plugin: configure AI Learning Check / Open edX Connector securely.

This plugin does not install the Django connector package. It writes the
AI_CONNECTOR_* values into both LMS and CMS Django settings so the existing
openedx_connector_plugin can authenticate server-to-server calls from AI Server.

Install/update:
  cp ai_learning_connector_env.py "$(tutor plugins printroot)/ai_learning_connector_env.py"
  tutor plugins enable ai_learning_connector_env
  tutor config save --set AI_CONNECTOR_HMAC_SECRET='<same-secret-as-AI-server>'
  tutor local restart lms cms lms-worker cms-worker

v25.9.16.5.8: Student Management runtime APIs are unified under the existing
openedx_connector_plugin. AI_STUDENT_INSIGHT_* remains only as a generated alias
for older endpoint paths; do not manage a second secret.
"""

from tutor import hooks


hooks.Filters.CONFIG_DEFAULTS.add_items(
    [
        ("AI_CONNECTOR_PUBLISH_USERNAME", "admin"),
        ("AI_CONNECTOR_ALLOW_ANONYMOUS_PUBLISH", "false"),
        ("AI_CONNECTOR_HMAC_SECRET", ""),
        ("AI_CONNECTOR_HMAC_SKEW_SECONDS", "300"),
        ("AI_CONNECTOR_ALLOWED_DOWNLOAD_HOSTS", ""),
        ("AI_CONNECTOR_COMPONENT_PUBLISH_ENABLED", "false"),
        ("AI_CONNECTOR_TAGGING_ENABLED", "true"),
        ("AI_CONNECTOR_TAG_TAXONOMY_EXPORT_ID", "ai-learning-check"),
        ("AI_CONNECTOR_TAG_TAXONOMY_NAME", "AI Learning Check"),
        ("AI_CONNECTOR_TAG_TAXONOMY_DESCRIPTION", "Tags automatically assigned by AI Learning Check Generator."),
        ("AI_CONNECTOR_AUTO_CREATE_ORG", "false"),
        ("AI_CONNECTOR_LIBRARY_ORG", "FPT"),
        ("AI_CONNECTOR_POST_PUBLISH_EVENTS_ENABLED", "false"),
        ("AI_CONNECTOR_ADMIN_GROUPS", "AI_ADMIN,AI Admin"),
        ("AI_CONNECTOR_SESSION_BRIDGE_ALLOWED_RETURN_HOSTS", "dash-cms.fpl.edu.vn"),
        ("AI_CONNECTOR_DEBUG_ERRORS", "false"),
        ("AI_CONNECTOR_MAX_BATCH_SIZE", "500"),
        ("AI_CONNECTOR_DEFAULT_ENROLLMENT_MODE", "audit"),
        ("AI_CONNECTOR_CREATED_USER_PASSWORD_MODE", "unusable"),
        ("AI_CONNECTOR_CREATED_USER_DEFAULT_PASSWORD", ""),
        # Deprecated compatibility settings. The generated Django settings below
        # alias these to AI_CONNECTOR_HMAC_SECRET so operators do not maintain two
        # secrets while old /api/ai-student-insight/v1/* URLs still exist.
        ("AI_STUDENT_INSIGHT_SHARED_SECRET", ""),
        ("AI_STUDENT_INSIGHT_HMAC_SKEW_SECONDS", "300"),
        ("AI_STUDENT_INSIGHT_MAX_BATCH_SIZE", "500"),
        ("AI_QUIZ_RUNTIME_ALLOWED_ORIGINS", "https://app.cms.fpl.edu.vn,https://cms.fpl.edu.vn,https://scms.fpl.edu.vn"),
    ]
)


_COMMON_CONNECTOR_SETTINGS = r'''
# AI Learning Check / Open edX Connector settings
# Generated by tutor plugin: ai_learning_connector_env
AI_CONNECTOR_PUBLISH_USERNAME = "{{ AI_CONNECTOR_PUBLISH_USERNAME }}"
AI_CONNECTOR_ALLOW_ANONYMOUS_PUBLISH = "{{ AI_CONNECTOR_ALLOW_ANONYMOUS_PUBLISH }}"
AI_CONNECTOR_HMAC_SECRET = "{{ AI_CONNECTOR_HMAC_SECRET }}"
AI_CONNECTOR_HMAC_SKEW_SECONDS = "{{ AI_CONNECTOR_HMAC_SKEW_SECONDS }}"
AI_CONNECTOR_ALLOWED_DOWNLOAD_HOSTS = "{{ AI_CONNECTOR_ALLOWED_DOWNLOAD_HOSTS }}"
AI_CONNECTOR_COMPONENT_PUBLISH_ENABLED = "{{ AI_CONNECTOR_COMPONENT_PUBLISH_ENABLED }}"
AI_CONNECTOR_TAGGING_ENABLED = "{{ AI_CONNECTOR_TAGGING_ENABLED }}"
AI_CONNECTOR_TAG_TAXONOMY_EXPORT_ID = "{{ AI_CONNECTOR_TAG_TAXONOMY_EXPORT_ID }}"
AI_CONNECTOR_TAG_TAXONOMY_NAME = "{{ AI_CONNECTOR_TAG_TAXONOMY_NAME }}"
AI_CONNECTOR_TAG_TAXONOMY_DESCRIPTION = "{{ AI_CONNECTOR_TAG_TAXONOMY_DESCRIPTION }}"
AI_CONNECTOR_AUTO_CREATE_ORG = "{{ AI_CONNECTOR_AUTO_CREATE_ORG }}"
AI_CONNECTOR_LIBRARY_ORG = "{{ AI_CONNECTOR_LIBRARY_ORG }}"
AI_CONNECTOR_POST_PUBLISH_EVENTS_ENABLED = "{{ AI_CONNECTOR_POST_PUBLISH_EVENTS_ENABLED }}"
AI_CONNECTOR_ADMIN_GROUPS = "{{ AI_CONNECTOR_ADMIN_GROUPS }}"
AI_CONNECTOR_SESSION_BRIDGE_ALLOWED_RETURN_HOSTS = "{{ AI_CONNECTOR_SESSION_BRIDGE_ALLOWED_RETURN_HOSTS }}"
AI_CONNECTOR_DEBUG_ERRORS = "{{ AI_CONNECTOR_DEBUG_ERRORS }}"
AI_CONNECTOR_MAX_BATCH_SIZE = "{{ AI_CONNECTOR_MAX_BATCH_SIZE }}"
AI_CONNECTOR_DEFAULT_ENROLLMENT_MODE = "{{ AI_CONNECTOR_DEFAULT_ENROLLMENT_MODE }}"
AI_CONNECTOR_CREATED_USER_PASSWORD_MODE = "{{ AI_CONNECTOR_CREATED_USER_PASSWORD_MODE }}"
AI_CONNECTOR_CREATED_USER_DEFAULT_PASSWORD = "{{ AI_CONNECTOR_CREATED_USER_DEFAULT_PASSWORD }}"

# Deprecated aliases kept for already-mounted /api/ai-student-insight/v1/* paths.
# Do not configure a different value from AI_CONNECTOR_HMAC_SECRET.
AI_STUDENT_INSIGHT_SHARED_SECRET = "{{ AI_STUDENT_INSIGHT_SHARED_SECRET }}" or AI_CONNECTOR_HMAC_SECRET
AI_STUDENT_INSIGHT_HMAC_SKEW_SECONDS = "{{ AI_STUDENT_INSIGHT_HMAC_SKEW_SECONDS }}"
AI_STUDENT_INSIGHT_MAX_BATCH_SIZE = "{{ AI_STUDENT_INSIGHT_MAX_BATCH_SIZE }}" or AI_CONNECTOR_MAX_BATCH_SIZE
AI_STUDENT_INSIGHT_DEFAULT_ENROLLMENT_MODE = AI_CONNECTOR_DEFAULT_ENROLLMENT_MODE
AI_QUIZ_RUNTIME_ALLOWED_ORIGINS = "{{ AI_QUIZ_RUNTIME_ALLOWED_ORIGINS }}"
'''

# Studio/CMS handles authoring/publish endpoints.
hooks.Filters.ENV_PATCHES.add_item(("openedx-cms-common-settings", _COMMON_CONNECTOR_SETTINGS))

# LMS handles Student Management runtime endpoints exposed by openedx_connector_plugin:
# /api/ai-connector/v1/users/resolve
# /api/ai-connector/v1/course-enrollment/enroll
# /api/ai-connector/v1/class-analytics
hooks.Filters.ENV_PATCHES.add_item(("openedx-lms-common-settings", _COMMON_CONNECTOR_SETTINGS))
