"""Tutor plugin: configure AI Learning Check CMS connector securely.

This plugin does not install the Django connector package. It only writes the
AI_CONNECTOR_* values into the generated CMS Django settings so the connector can
read them without a manual docker-compose.override.yml.

Install:
  cp ai_learning_connector_env.py "$(tutor plugins printroot)/ai_learning_connector_env.py"
  tutor plugins enable ai_learning_connector_env
  tutor config save --set AI_CONNECTOR_HMAC_SECRET='<same-secret-as-AI-server>'
  tutor local restart cms cms-worker
"""

from tutor import hooks


hooks.Filters.CONFIG_DEFAULTS.add_items(
    [
        ("AI_CONNECTOR_PUBLISH_USERNAME", "admin"),
        ("AI_CONNECTOR_ALLOW_ANONYMOUS_PUBLISH", "false"),
        ("AI_CONNECTOR_HMAC_SECRET", ""),
        ("AI_CONNECTOR_HMAC_SKEW_SECONDS", "300"),
        ("AI_CONNECTOR_ALLOWED_DOWNLOAD_HOSTS", ""),
        ("AI_CONNECTOR_COMPONENT_PUBLISH_ENABLED", "false"),
        ("AI_CONNECTOR_TAGGING_ENABLED", "true"),
        ("AI_CONNECTOR_TAG_TAXONOMY_EXPORT_ID", "ai-learning-check"),
        ("AI_CONNECTOR_TAG_TAXONOMY_NAME", "AI Learning Check"),
        ("AI_CONNECTOR_TAG_TAXONOMY_DESCRIPTION", "Tags automatically assigned by AI Learning Check Generator."),
        ("AI_CONNECTOR_AUTO_CREATE_ORG", "false"),
        ("AI_CONNECTOR_POST_PUBLISH_EVENTS_ENABLED", "false"),
    ]
)


hooks.Filters.ENV_PATCHES.add_item(
    (
        "openedx-cms-common-settings",
        r'''
# AI Learning Check Connector settings
# Generated by tutor plugin: ai_learning_connector_env
AI_CONNECTOR_PUBLISH_USERNAME = "{{ AI_CONNECTOR_PUBLISH_USERNAME }}"
AI_CONNECTOR_ALLOW_ANONYMOUS_PUBLISH = "{{ AI_CONNECTOR_ALLOW_ANONYMOUS_PUBLISH }}"
AI_CONNECTOR_HMAC_SECRET = "{{ AI_CONNECTOR_HMAC_SECRET }}"
AI_CONNECTOR_HMAC_SKEW_SECONDS = "{{ AI_CONNECTOR_HMAC_SKEW_SECONDS }}"
AI_CONNECTOR_ALLOWED_DOWNLOAD_HOSTS = "{{ AI_CONNECTOR_ALLOWED_DOWNLOAD_HOSTS }}"
AI_CONNECTOR_COMPONENT_PUBLISH_ENABLED = "{{ AI_CONNECTOR_COMPONENT_PUBLISH_ENABLED }}"
AI_CONNECTOR_TAGGING_ENABLED = "{{ AI_CONNECTOR_TAGGING_ENABLED }}"
AI_CONNECTOR_TAG_TAXONOMY_EXPORT_ID = "{{ AI_CONNECTOR_TAG_TAXONOMY_EXPORT_ID }}"
AI_CONNECTOR_TAG_TAXONOMY_NAME = "{{ AI_CONNECTOR_TAG_TAXONOMY_NAME }}"
AI_CONNECTOR_TAG_TAXONOMY_DESCRIPTION = "{{ AI_CONNECTOR_TAG_TAXONOMY_DESCRIPTION }}"
AI_CONNECTOR_AUTO_CREATE_ORG = "{{ AI_CONNECTOR_AUTO_CREATE_ORG }}"
AI_CONNECTOR_POST_PUBLISH_EVENTS_ENABLED = "{{ AI_CONNECTOR_POST_PUBLISH_EVENTS_ENABLED }}"
''',
    )
)
