export { BankDashboardPage } from './pages/BankDashboardPage'
export { DepartmentsPage } from './pages/DepartmentsPage'
export { DepartmentSubjectsPage } from './pages/DepartmentSubjectsPage'
export { SubjectVersionsPage } from './pages/SubjectVersionsPage'
export { SubjectVersionChaptersPage } from './pages/SubjectVersionChaptersPage'
export { ChapterWorkspacePage } from './pages/ChapterWorkspacePage'
export { BankHistoryPage } from './pages/BankHistoryPage'
